/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LeitorDigital.java
 *
 * Created on 06/05/2011, 07:39:56
 */
package br.com.pensino.digital.ui;

import br.com.pensino.ui.panel.MainPanel;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author emerson
 */
public class LeitorDigital extends javax.swing.JFrame {

    /** Creates new form LeitorDigital */
    public LeitorDigital() {
        initComponents();
        // apenas para testes
        this.setContentPane(new JPanel() {

            @Override
            public void paintComponent(Graphics g) {
                super.paintComponents(g);
                Image imagem = new ImageIcon("leitor-digital-bg.PNG").getImage();
                g.drawImage(imagem, 0, 0, this);
            }
        });
        this.getContentPane().removeAll();
        this.getContentPane().add(new MainPanel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pensino : Leitor Digital");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("framePrincipal"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-610)/2, (screenSize.height-610)/2, 610, 610);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LeitorDigital().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
