/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LeitorDigital.java
 *
 * Created on 06/05/2011, 07:39:56
 */
package br.com.pensino.digital.ui;

import br.com.pensino.ui.panel.MainPanel;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author emerson
 */
public class LeitorDigital extends javax.swing.JFrame {
    
    private MainPanel mainPanel = new MainPanel();

    /** Creates new form LeitorDigital */
    public LeitorDigital() {
        initComponents();
        
        // apenas para testes
        this.setContentPane(new JPanel() {

            @Override
            public void paintComponent(Graphics g) {
                super.paintComponents(g);
                Image imagem = new ImageIcon("leitor-digital-bg.PNG").getImage();
                g.drawImage(imagem, 0, 0, this);
            }
        });
        java.awt.GridBagConstraints gridBagConstraints;
        
        getContentPane().setLayout(new java.awt.GridBagLayout());
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPanel.setMinimumSize(new java.awt.Dimension(500, 730));
        mainPanel.setPreferredSize(new java.awt.Dimension(500, 730));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        
        getContentPane().add(mainPanel, gridBagConstraints);
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-610)/2, (screenSize.height-610)/2, 610, 610);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middleContainer = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pensino : Leitor Digital");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 730));
        setName("framePrincipal"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        middleContainer.setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().add(middleContainer, new java.awt.GridBagConstraints());

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-610)/2, (screenSize.height-476)/2, 610, 476);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LeitorDigital().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane middleContainer;
    // End of variables declaration//GEN-END:variables
}
