/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassStartPanel.java
 *
 * Created on 20/05/2011, 07:49:17
 */
package br.com.pensino.ui.components;

import java.awt.GridLayout;

/**
 *
 * @author emiliowl
 */
public class ClassStartPanel extends javax.swing.JPanel {

    /** Creates new form ClassStartPanel */
    public ClassStartPanel() {
        initComponents();
        this.setLayout(new GridLayout(3, 2));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(550, 170));
        setMinimumSize(new java.awt.Dimension(550, 170));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(550, 170));
        setLayout(new java.awt.GridLayout());

        jLabel1.setText("Código:");
        add(jLabel1);

        jLabel2.setText("-");
        add(jLabel2);

        jLabel3.setText("Nome:");
        add(jLabel3);

        jLabel4.setText("-");
        add(jLabel4);

        jLabel5.setText("Disciplina:");
        add(jLabel5);

        jLabel6.setText("-");
        add(jLabel6);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
