/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassStartPanel.java
 *
 * Created on 20/05/2011, 07:49:17
 */
package br.com.pensino.ui.components;

import br.com.pensino.domain.model.Person;
import br.com.pensino.ui.exception.EmployeeNotFoundException;
import br.com.pensino.ui.exception.PersonNotFoundException;
import br.com.pensino.ui.exception.StudentNotFoundException;
import br.com.pensino.utils.db.EmployeeDAO;
import br.com.pensino.utils.db.StudentDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emiliowl
 */
public class MiddleRegisterPanel extends javax.swing.JPanel {

    String[] tableHeader = new String[]{"NOME", "DOCUMENTO"};
    EmployeeDAO employeeDAO;
    StudentDAO studentDAO;

    /** Creates new form ClassStartPanel */
    public MiddleRegisterPanel(EmployeeDAO employeeDAO, StudentDAO studentDAO) {
        this.employeeDAO = employeeDAO;
        this.studentDAO = studentDAO;
        initComponents();
        init();
        loadTableWithPerson(employeeDAO.all());
    }

    public Person getSelectedPerson() throws PersonNotFoundException {
        if (jTable1.getSelectedRow() > -1) {
            String personDocument = (String)jTable1.getValueAt(jTable1.getSelectedRow(), 1);
            if (jComboBox1.getSelectedItem().equals("Professores")) {    
                return employeeDAO.find(EmployeeDAO.By.DOCUMENT, personDocument).get(0);
            } else if (jComboBox1.getSelectedItem().equals("Alunos")) {
                return studentDAO.find(StudentDAO.By.DOCUMENT, personDocument).get(0);
            }
        }
        if (jComboBox1.getSelectedItem().equals("Professores")) {
            throw new EmployeeNotFoundException();
        } else {
            throw new StudentNotFoundException();
        }
    }

    private void init() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Alunos");
        jComboBox1.addItem("Professores");
        jComboBox1.setSelectedItem("Professores");
    }

    private void loadTableWithPerson(List<? extends Person> dataToLoad) {
        if (dataToLoad == null) {
            dataToLoad = new ArrayList<Person>();
        }
        String[][] tableData = new String[dataToLoad.size()][];
        for (int i = 0; i < dataToLoad.size(); i++) {
            Person person = dataToLoad.get(i);
            String[] personString = new String[2];
            personString[0] = person.getFirstName() + " " + person.getLastName();
            personString[1] = person.getDocument();
            tableData[i] = personString;
        }
        this.jTable1.setModel(new DefaultTableModel(tableData, tableHeader));
        validate();
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(365, 200));
        setMinimumSize(new java.awt.Dimension(365, 200));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(365, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(300, 28));
        jComboBox1.setMinimumSize(new java.awt.Dimension(300, 28));
        jComboBox1.setPreferredSize(new java.awt.Dimension(300, 28));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 28));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(310, 100));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem() != null) {
            if (jComboBox1.getSelectedItem().equals("Professores")) {
                loadTableWithPerson(employeeDAO.all());
            } else if (jComboBox1.getSelectedItem().equals("Alunos")) {
                loadTableWithPerson(studentDAO.all());
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
